### ISSUE TITLE
troika-three-text: Not working with three@0.170.0

### ISSUE THREAD

**Issue by danielesteban** [protectwise/troika#335]
troika-three-text throws an error with the latest three revision (0.170.0):
```
Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at m (troika-three-utils.esm.js:22:17)
    at troika-three-utils.esm.js:357:20
    at es.a (troika-three-utils.esm.js:169:24)
    at $t (three.module.js:30552:14)
    at three.module.js:30817:15
    at nc.renderBufferDirect (three.module.js:29615:20)
    at Kt (three.module.js:30492:11)
    at Zt (three.module.js:30461:6)
    at Xt (three.module.js:30312:41)
    at nc.render (three.module.js:30128:5)
```

You can reproduce it here:
https://jsfiddle.net/jng7u62b/54/

With three@0.169.0 works as intended:
https://jsfiddle.net/jng7u62b/55/

**Comment by lojjic** [comment]
Thanks! ThreeJS changed how `material.type` is defined (simple property to a getter) and that made it so the text material couldn't get the base material shaders. It's now fixed and published in `0.50.3`.

https://jsfiddle.net/6t0f7h8u/1/
